from __future__ import annotations

import copy as copy

import numpy as np
from numpy import ma

import quasardb as quasardb

__all__: list = list()

def _ensure_ctype(self, idx, ctype): ...
def _legacy_current_row(self): ...
def _legacy_next_row(self, table): ...
def _legacy_push(self): ...
def _legacy_set_blob(self, idx, x): ...
def _legacy_set_double(self, idx, x): ...
def _legacy_set_int64(self, idx, x): ...
def _legacy_set_string(self, idx, x): ...
def _legacy_set_timestamp(self, idx, x): ...
def _legacy_start_row(self, table, x): ...
def _wrap_fn(old_fn, replace_fn): ...
def extend_writer(x):
    """

    Extends the writer with the "old", batch inserter API. This is purely
    a backwards compatibility layer, and we want to avoid having to maintain that
    in C++ with few benefits.

    """
