[build-system]
requires = [
    "setuptools>=47",
    "wheel",
    "ninja",
    "cmake>=3.9.4",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-s", "-x"]
xfail_strict = true
filterwarnings = []
testpaths = ["tests"]
