#!/bin/sh

CMD="qdb/bin/qdbd"
ARGS="-a 127.0.0.1:28360 --security=false --storage-engine=transient --log-level=debug -r qdb/db"
SECURE_ARGS="-a 127.0.0.1:28361 --security=true --cluster-private-file=cluster-secret-key.txt --user-list=users.txt --storage-engine=transient --log-level=debug -r qdb/securedb"

echo "Cleaning up..."
pkill -SIGKILL -f qdbd
rm -rf qdb/db \
    && rm -rf qdb/securedb \
    && mkdir -p qdb/db \
    && mkdir -p qdb/securedb

echo "Starting qdbd..."
$CMD $ARGS 1>qdbd.out.txt 2>qdbd.err.txt &

echo "Starting qdbd (secure)..."

$CMD $SECURE_ARGS 1>qdbd.secure.out.txt 2>qdbd.secure.err.txt &
