#!/bin/sh

pkill -SIGKILL -f qdbd

echo "qdbd.out.txt: "
cat qdbd.out.txt

echo "qdbd.err.txt: "
cat qdbd.err.txt

echo "qdbd.secure.out.txt: "
cat qdbd.secure.out.txt

echo "qdbd.secure.err.txt: "
cat qdbd.secure.err.txt
