import datetime

from ._entry import ExpirableEntry

class Blob(ExpirableEntry):
    def compare_and_swap(self, new_content: str, comparand: str) -> bytes: ...
    def get(self) -> bytes: ...
    def get_and_remove(self) -> bytes: ...
    def get_and_update(self, data: str) -> bytes: ...
    def put(self, data: str) -> None: ...
    def remove_if(self, comparand: str) -> None: ...
    def update(
        self,
        data: str,
        expiry: datetime.datetime = datetime.datetime.fromtimestamp(0),
    ) -> None: ...
