from __future__ import annotations

from typing import Any

# import datetime

class QueryContinuous:
    def __iter__(self) -> QueryContinuous: ...
    def __next__(self) -> list[dict[str, Any]]: ...
    def probe_results(self) -> list[dict[str, Any]]: ...
    def results(self) -> list[dict[str, Any]]: ...
    # def run(
    #     self,
    #     mode: qdb_query_continuous_mode_type_t,
    #     pace: datetime.timedelta,
    #     query: str,
    # ) -> None: ...
    def stop(self) -> None: ...
