from ._entry import ExpirableEntry

class Double(ExpirableEntry):
    def add(self, addend: float) -> float: ...
    def get(self) -> float: ...
    def put(self, double: float) -> None: ...
    def update(self, double: float) -> None: ...
