from ._entry import ExpirableEntry

class Integer(ExpirableEntry):
    def add(self, addend: int) -> int: ...
    def get(self) -> int: ...
    def put(self, integer: int) -> None: ...
    def update(self, integer: int) -> None: ...
