from typing import Any

class Perf:
    def clear(self) -> None: ...
    def disable(self) -> None: ...
    def enable(self) -> None: ...
    def get(self, flame: bool = False, outfile: str = "") -> Any: ...
