from __future__ import annotations

import typing

class Reader:
    def __enter__(self) -> Reader: ...
    def __exit__(self, exc_type: object, exc_value: object, exc_tb: object) -> None: ...
    def __iter__(self) -> typing.Iterator[dict[str, object]]: ...
    def get_batch_size(self) -> int: ...
