import datetime

from ._entry import ExpirableEntry

class String(ExpirableEntry):
    def compare_and_swap(self, new_content: str, comparand: str) -> str: ...
    def get(self) -> str: ...
    def get_and_remove(self) -> str: ...
    def get_and_update(self, data: str) -> str: ...
    def put(self, data: str) -> None: ...
    def remove_if(self, comparand: str) -> None: ...
    def update(self, data: str, expiry: datetime.datetime = ...) -> None: ...
