import datetime

from ._entry import ExpirableEntry

class Timestamp(ExpirableEntry):
    def add(self, addend: datetime.datetime) -> datetime.datetime: ...
    def get(self) -> datetime.datetime: ...
    def put(self, timestamp: datetime.datetime) -> None: ...
    def update(self, timestamp: datetime.datetime) -> None: ...
