agents:
  queue: "default-{queue}"

# retry:
#   automatic:
#       limit: 3

label: "{name} ({slug})"
key: "build-{slug}"

commands:
  - echo \"+++ Start Services\"
  - bash scripts/tests/setup/start-services.sh
  - echo \"+++ Run Tests\"
  - bash scripts/cicd/20.test.sh
  # - echo \"+++ Run build\"
  # - bash scripts/cicd/10.build.sh

wait: ~

plugins:
  - bureau14/qdb-artifacts#master:
      download:
        clean: true
        projects:
          - project_id: "quasardb-build"
            output-dir: "qdb"
            extract: true
            files:
              - "*-c-api.tar.zst!*"
              - "*-server.tar.zst!*"
              - "*-utils.tar.zst!*"
      upload:
        files:
          - "dist/quasardb-*.whl"
          - "dist/doc.tar.gz"
        base_dir: "dist"
      promote: {}
  - igorniebylski/junit-annotate#master:
      local-artifacts: test-results/pytest.xml
      always-annotate: true
      report-skipped: true
      context: build-{slug}
