agents:
  queue: "default-{queue}"

retry:
  automatic:
    - signal_reason: agent_stop
      limit: 3

label: "{name} ({slug})"
key: "build-{slug}"

commands:
  - echo \"+++ Start Services\"
  - bash scripts/tests/setup/start-services.sh
  - echo \"+++ Run Tests\"
  - bash scripts/teamcity/20.test.sh
  - echo \"+++ Stop Services\"
  - bash scripts/tests/setup/stop-services.sh
  - echo \"+++ Run build\"
  - bash scripts/teamcity/10.build.sh

plugins:
  - bureau14/qdb-artifacts#artifact-dependency:
      download:
        project_id: "quasardb"
        output-dir: "qdb"
        extract: true
        clean: true
        files:
          - "*-c-api.tar.zst!*"
          - "*-server.tar.zst!*"
          - "*-utils.tar.zst!*"
      upload:
        files:
          - "dist/quasardb*.whl"
          - "dist/quasardb*.tar.gz"
          - "dist/doc.tar.gz"
          - "dist/quasardb*.egg"
      promote: {}