agents:
  queue: "default-{queue}"

label: "Test ({slug})"
key: "test-{slug}"

commands:
  - "echo \"+++ Start Services\""
  - "scripts/tests/setup/start-services.sh"
  - "echo \"+++ Run Tests\""
  - "scripts/teamcity/20.test.sh"
  - "echo \"+++ Stop Services\""
  - "scripts/tests/setup/stop-services.sh"
  - "echo \"+++ Run build\""
  - "scripts/teamcity/10.build.sh"  

plugins:
  - docker-compose#v5.12.1:
      run: pypa
      config: docker/docker-compose.yml
      propagate-environment: true
      propagate-uid-gid: true

  - bureau14/qdb-artifacts#artifact-dependency:
      download:
        project_id: "quasardb"
        variant: "{dependency_slug}"
        git_ref: "{ref}"
        output-dir: "qdb"
        extract: true
        clean: true
        files:
          - "*-c-api.tar.zst!*"
          - "*-server.tar.zst!*"
          - "*-utils.tar.zst!*"
      upload:
        files: "dist/*"
        variant: "{slug}"
        git_ref: "{ref}"
      promote:
        variant: "{slug}"
        git_ref: "{ref}"
