name: Format check

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.pyi'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - '**.pyi'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r scripts/github_actions/requirements.txt

      - name: Run black on Python files
        run: |
          black --check --verbose .

      - name: Run black on stub files
        run: |
          black --include '\.pyi$' --check --verbose .

  typing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r scripts/github_actions/requirements.txt
          pip install -r dev-requirements.txt

      - name: Run mypy
        run: |
          mypy --check quasardb
